baseurl = "https://humboldt-wi.github.io/blog/"
title = "Institute of Infomation Systems at HU-Berlin"
theme = "hugo-universal-theme"
themesDir = "themes"
publishDir = "docs"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-112025566-1"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "News"
    url  = "/news/"
    weight = 2

[[menu.main]]
    name = "Contributors"
    identifier = "/contributors/"
    url  = "/contributors/"
    weight = 3


[[menu.main]]
    name = "research"
    identifier = "/research/"
    url  = "/research/"
    weight = 6

[[menu.main]]
    name = "Contact"
    identifier = "/contact/"
    url  = "/contact/"
    weight = 7

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/wisample/blog"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/WinfoHUB/"
    pre = "<i class='fa fa-2x fa-facebook'></i>"




[params]
    viewMorePostLink = "/blog/"
    author = "SocialMediaTeam"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    #googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

	#latitude = "52.521166"
    #longitude = "13.402748"
	#direction = "Wirtschaftswissenschaftliche Fakultät, Spandauer Str. 1, 10178 Berlin"


    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"





    copyright = "Copyright (c) 2017, Chair of Information System at HU-Berlin; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logoGross.png"



[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +49 30 2093-5742 or bujarek@hu-berlin.de.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false
    month = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.


[params.see_more]
    enable = true
    icon = "fa fa-university"
    title = "Chair of Information Systems"
    subtitle = "Find more information about us"
    link_url = "https://www.wiwi.hu-berlin.de/en/professuren/quantitativ/wi"
    link_text = "Official Homepage"

[params.clients]
    enable = false
    icon = "fa fa-university"
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Recent from our Chair"
    subtitle = "" #Here are recent research findings from our institute.


[Taxonomies]
  tag = "tags"
  category = "categories"
  month = "month"
